services:
  server:
    build:
      context: .
      dockerfile: .docker/server/Dockerfile
    container_name: node-otel-server
    ports:
      - "9010:9010"
    volumes:
      - type: bind
        source: ./server
        target: /app/server
      - type: bind
        source: ./tracing
        target: /app/tracing
      - type: bind
        source: ./tsconfig.json
        target: /app/tsconfig.json
    depends_on:
      - jaeger

  jaeger:
    build:
      context: .
      dockerfile: .docker/jaeger/Dockerfile
    container_name: node-otel-jaeger
    ports:
      - "16686:16686" # UI
      - "4318:4318" # OTLP HTTP
